// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalFerias.Data;

#nullable disable

namespace PortalFerias.Migrations
{
    [DbContext(typeof(DbPortalFeriasContext))]
    [Migration("20260213124056_UpdateHomeModernContent")]
    partial class UpdateHomeModernContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortalFerias.Models.Apresentacao_BC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Pagina")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Texto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Apresentacao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Pagina = "Home",
                            Texto = "<div class='main-wrapper'>\r\n    <h1 class='titulo-home'>Bem-vindo!</h1>\r\n    \r\n    <div style='width:60px; height:4px; background-color:#0d6efd; margin:0 auto 25px auto; border-radius:2px;'></div>\r\n\r\n    <p class='subtitulo-home'>\r\n        Esta é uma página onde pode pesquisar o local ideal para passar as suas férias.\r\n    </p>\r\n\r\n    <div class='img-container-ferias'>\r\n        <img src='/images/ferias.jpg' alt='Destino de Férias'>\r\n    </div>\r\n\r\n    <p style='margin-top: 30px; color: #888; font-style: italic;'>\r\n        Obrigado pela preferência.\r\n    </p>\r\n\r\n    <div class='mt-4'>\r\n        <a href='/Home/Destinos' class='btn btn-primary btn-lg px-5 shadow-sm' \r\n           style='border-radius:50px; font-weight:600; transition: 0.3s;'>\r\n           Explorar Destinos\r\n        </a>\r\n    </div>\r\n</div>"
                        });
                });

            modelBuilder.Entity("PortalFerias.Models.Destino_BC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Preco")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Destinos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Venha conhecer a capital de um dos países mais ricos a nível cultural e natural da América do Sul, a Argentina. Visite Buenos Aires, durante 9dias/ 7noites com partidas diárias de Lisboa em voo regular, via Madrid.",
                            Pais = "Argentina",
                            Preco = 1321.0
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Natal ou Pipa! A escolha é sua! Aproveite esta super promoção e faça já a sua reserva. Partidas aos domingos em Julho a Setembro.",
                            Pais = "Brasil",
                            Preco = 680.0
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Aproveite esta super promoção e marque umas férias em Porto Seguro ou em Arraial d'Ajuda! Válido para partidas de Lisboa em voo especial terra Brasil aos domingos.",
                            Pais = "Brasil",
                            Preco = 750.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
